---
name: TR Scott
layout: default
permalink: /:year/:month/:day/:title
---

# My Jekyll site

Welcome to my Jekyll site

# Includes an icon in the footer for each username you enter
footer-links:
  email:mailto:info@trscott.co.uk
  twitter: tomscott230

