---
name: TR Scott
layout: default
permalink: /:year/:month/:day/:title
---

# My Jekyll site

Welcome to my Jekyll site

# Sitemap
gems:
  - jekyll-sitemap
  
#Homepage post pagination  
  paginate: 5

